### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by ibebbs** [ukparliament/Data.Api.FixedQuery#218]
Hi,

Is this endpoint still live?  If so, are you able to provide a link to a "Getting Started" guide? The closest I've found is [this post on Medium](https://medium.com/@langsamu/api-parliament-uk-7b87597019a4) but, while it describes the various endpoints, it doesn't provide any information on how one might get started running arbitrary queries against this endpoint.

By way of example, I have tried running [this query](https://github.com/ukparliament/Query/blob/master/Parliament.Data.Api.FixedQuery/Sparql/formal_body_by_id.sparql) in [SPARQLer](http://sparql.org/sparql.html) but, no matter what I do, I don't seem to be able to get a query to run successfully.

It would be a great bootstrap for people who want to use this endpoint if you could show a couple of example queries along with instructions on how they might be executed.

Thanks,
  Ian

**Comment by johnhzhu** [comment]
Hi Ian,

Please try your sparql query on https://api.parliament.uk/sparql . Some
example queries here:
https://ukparliament.github.io/ontologies/procedure/meta/queries/

Regards,
Jianhan

**Comment by ibebbs** [comment]
Wow, Google (ok DuckDuckGo) completely failed me here.

Thanks for the quick reply, I'll give it a go now.
